//SimpleComRegistered.idl
[
	// 🔹 Type Library GUID (Matches the assembly-level GUID in C#)
	// This uniquely identifies the entire COM library and should match the [assembly: Guid(...)] in C#.
	uuid(D068F42B-A556-4188-8FF2-792AAF6D0B42),
		version(1.0)
]
library SimpleComRegisteredLibrary
{
	// Import standard COM definitions
import "oaidl.idl";
import "ocidl.idl";

	[
		object,
			// 🔹 Interface GUID (Matches the interface GUID in C#)
			// This uniquely identifies the ISimpleComRegistered interface and should match the [Guid(...)] on the C# interface.
			uuid(D9CA3BE3-610E-4251-82B7-11FEFAA45F33),
			oleautomation
	]
		interface ISimpleComRegistered : IUnknown
	{
		// The method exposed to COM (returns a BSTR, which is the COM equivalent of a string)
		HRESULT Test([out, retval] BSTR* result);
	};

	[
		// 🔹 Class GUID (Matches the class GUID in C#)
		// This uniquely identifies the SimpleComRegistered class and should match the [Guid(...)] on the C# class.
		uuid(77676CBD-E536-4B98-9841-0AC794051191),
			version(1.0)
	]
		coclass SimpleComRegistered
	{
		// 🔹 Specifies that the ISimpleComRegistered interface is the default interface for this COM class
		[default] interface ISimpleComRegistered;
	};
};